# Generated by Django 3.2.15 on 2023-06-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=200)),
                ('password', models.CharField(default='NA', max_length=200)),
                ('email', models.CharField(default='NA', max_length=200)),
            ],
        ),
    ]
